# OrbitRender English translations

diagnostics-have-not-been-run = Diagnostics have not been run.
click-run-diagnostics-to-check-ffmpeg-the-output-folder = Click Run diagnostics to check FFmpeg, the output folder, the encoder, and game audio.
configure-the-defaults-used-when-exporting-a-video-per = Configure the defaults used when exporting a video. Per-export settings can be changed from the Export Video window.
render-options = Render options
visible-components = Visible components
encoding = Encoding
files-troubleshooting = Files & troubleshooting
reset-render-settings-to-defaults = Reset render settings to defaults
preset = Preset
width = Width
height = Height
bitrate = Bitrate
preset-output = Preset output: {0} × {1} | target {2} FPS | video {3} FPS | {4} Mbps
ingame-fps = InGame FPS
video-fps = Video FPS
end-delay-seconds = End delay (seconds)
capture-audio = Capture audio
show-render-preview = Show preview while rendering
low-load-render-preview = Low-load preview (15 FPS)
bga-mode-hide-tiles-planets-hit-sounds = BGA mode (hide tiles, planets & hit sounds)
open-output-folder-after-render = Open output folder after render
show-planet-rings = Show planet rings
show-song-title = Show song title
show-countdown = Show countdown
show-result-text-hit-judgments-stay-hidden = Show result text (hit judgments stay hidden)
show-hit-judgments = Show hit judgments
output-folder = Output folder
ffmpeg-executable = FFmpeg executable
ffmpeg-setup = FFmpeg setup
install-ffmpeg = Install FFmpeg
not-now = Not now
browse = Browse...
diagnostics = Diagnostics
run-this-before-reporting-an-export-problem-it-checks-f = Run this before reporting an export problem. It checks FFmpeg, the output folder, the encoder, and game audio.
run-diagnostics = Run diagnostics
copy-report = Copy report
diagnostics-failed-unexpectedly = Diagnostics failed unexpectedly.
orbitrender-is-not-ready-yet = OrbitRender is not ready yet.
a-render-is-already-in-progress = A render is already in progress.
open-a-custom-level-then-render = Open a Custom Level, then Render.
open-a-custom-level-then-press-f6-to-render = Open a Custom Level, then press F6 to render.
ffmpeg-installation-requires-your-confirmation-before-r = FFmpeg installation requires your confirmation before rendering.
preparing-render = Preparing {0}x{1} | target {2} fps | video {3} fps ({4} Mbps, {5})...
checking-value-encoder = Checking {0} encoder...
ffmpeg-could-not-initialize-the-selected-encoder = FFmpeg could not initialize the selected encoder.
hardware-encoder-failed-use-software-encoder-for-this-r = Hardware encoder failed. Use Software encoder for this render?
encoder-preflight-failed-value = Encoder preflight failed: {0}
checking-software-encoder-for-this-render = Checking Software encoder for this render...
render-cancelled-hardware-encoder-was-unavailable = Render cancelled; hardware encoder was unavailable.
progress-percent = {0:F1}%
progress-frames = {0} / {1} frames   •   {2:F1} fps
progress-eta = ETA {0}   •   finishes around {1}
progress-speed = {0:F2}x realtime   •   elapsed {1}
progress-toast = Rendering  {0:F1}%  |  {1} / {2} frames  |  {3:F1} fps  |  ETA {4}
render-cancelled = Render cancelled.
rendering-summary = Rendering {0}x{1} | target {2} fps | video {3} fps
finalizing-container = Finalizing {0}...
completed-frames = Completed: {0} frames.
audio-mix-was-silent-check-game-sound-settings =  Audio mix was silent; check game sound settings.
render-force-cancelled = Render force-cancelled.
render-failed-value = Render failed: {0}
cleanup-failed-value = Cleanup failed: {0}
diagnostics-found-value-error-s-and-value-warning-s = Diagnostics found {0} error(s) and {1} warning(s).
diagnostics-passed-with-value-warning-s = Diagnostics passed with {0} warning(s).
all-diagnostics-passed = All diagnostics passed.
export-video = Export Video
export-video-selection = Export Video Selection
select-at-least-two-tiles-to-export-a-selection = Select at least two tiles with Shift + Click first.
choose-the-settings-for-this-video-export = Choose the settings for this video export.
save-these-values-as-the-default-renderer-settings = Save these values as the default renderer settings
cancel = Cancel
ingame-fps-must-be-between-15-and-1024 = InGame FPS must be between 15 and 1024.
video-fps-must-be-between-15-and-240 = Video FPS must be between 15 and 240.
width-height-and-bitrate-must-be-valid-numbers = Width, height and bitrate must be valid numbers.
custom-values-are-outside-the-supported-ranges = Custom values are outside the supported ranges.
width-and-height-must-be-even-numbers = Width and height must be even numbers.
end-delay-must-be-between-0-and-30-seconds = End delay must be between 0 and 30 seconds.
select-render-output-folder = Select render output folder
select-ffmpeg-executable = Select FFmpeg executable
frames = FRAMES
speed = SPEED
complete = Complete
eta = ETA
done = Done
time-spent = TIME SPENT
copy-path = Copy path
the-render-window-will-update-when-the-next-stage-is-re = The render window will update when the next stage is ready.
hold-esc-for-1-second-to-cancel = Hold Esc for 1 second to cancel
cancel-render = Cancel render
preparing = PREPARING
rendering = RENDERING
finalizing = FINALIZING
completed = COMPLETED
cancelled = CANCELLED
failed = FAILED
status = STATUS
preparing-your-export = Preparing your export
rendering-video = Rendering video
finishing-video = Finishing video
export-complete = Export complete
render-cancelled-status = Render cancelled
render-failed-status = Render failed
render-status = Render status
output-file = Output: {0}
duration-hours = {0}:{1:D2}:{2:D2}
duration-minutes = {0}:{1:D2}
encoder-confirmation = ENCODER CONFIRMATION
the-selected-hardware-encoder-could-not-be-initialized = The selected hardware encoder could not be initialized.
use-software-encoder-for-this-render-your-saved-encoder = Use Software encoder for this render? Your saved encoder setting will not be changed.
use-software-and-continue = Use Software and continue
ffmpeg-installation = FFMPEG INSTALLATION
installing-ffmpeg = INSTALLING FFMPEG
orbitrender-needs-ffmpeg-to-export-videos-download-the = OrbitRender needs FFmpeg to export videos. Download the platform-compatible binary now?
downloading-ffmpeg-for-this-platform-the-renderer-will = Downloading FFmpeg for this platform. The renderer will be ready when the download finishes.
the-download-comes-from-the-ffmpeg-build-provider-and-i = The download comes from the FFmpeg build provider and is saved inside the mod folder. An internet connection is required.
custom = Custom
preview = Preview
encoding-speed = Encoding speed
maximum = Maximum
balanced = Balanced
quality = Quality
video-encoder = Video encoder
auto = Auto
software = Software
video-codec = Video codec
video-bit-depth = Video bit depth
ffmpeg-is-not-installed-waiting-for-your-confirmation-t = FFmpeg is not installed. Waiting for your confirmation to download it.
downloading-ffmpeg-for-this-platform = Downloading FFmpeg for this platform...
extracting-ffmpeg = Extracting the FFmpeg archive...
installing-ffmpeg-binary = Installing the FFmpeg binary...
ffmpeg-progress-percent = {0:F1}%
ffmpeg-progress-waiting-for-size = Downloading...
ffmpeg-download-size = {0:F1} / {1:F1} MB
ffmpeg-download-size-unknown = Download size unavailable
ffmpeg-could-not-be-installed-automatically-value-check = FFmpeg could not be installed automatically: {0}. Check the log or set FFmpeg executable manually.
ffmpeg-installation-was-skipped-set-ffmpeg-executable-m = FFmpeg installation was skipped. Set FFmpeg executable manually or install it below.
