# OrbitRender Korean translations

diagnostics-have-not-been-run = 진단을 아직 실행하지 않았습니다.
click-run-diagnostics-to-check-ffmpeg-the-output-folder = 진단 실행을 눌러 FFmpeg, 출력 폴더, 인코더 및 게임 오디오를 확인하세요.
configure-the-defaults-used-when-exporting-a-video-per = 영상 내보내기에 사용할 기본값입니다. 개별 내보내기 설정은 영상 내보내기 창에서 바꿀 수 있습니다.
render-options = 렌더 옵션
visible-components = 표시할 구성 요소
encoding = 인코딩
files-troubleshooting = 파일 및 문제 해결
reset-render-settings-to-defaults = 렌더링 설정을 기본값으로 복원
preset = 프리셋
width = 너비
height = 높이
bitrate = 비트레이트
preset-output = 프리셋 출력: {0} × {1} | 게임 {2} FPS | 영상 {3} FPS | {4} Mbps
ingame-fps = 인게임 FPS
video-fps = 영상 FPS
end-delay-seconds = 종료 지연(초)
capture-audio = 오디오 캡처
bga-mode-hide-tiles-planets-hit-sounds = BGA 모드 (타일, 행성 및 타격음 숨기기)
open-output-folder-after-render = 렌더 후 출력 폴더 열기
show-planet-rings = 행성 고리 표시
show-song-title = 곡 제목 표시
show-countdown = 카운트다운 표시
show-result-text-hit-judgments-stay-hidden = 결과 텍스트 표시 (판정은 숨김)
show-hit-judgments = 판정 표시
output-folder = 출력 폴더
ffmpeg-executable = FFmpeg 실행 파일
ffmpeg-setup = FFmpeg 설정
install-ffmpeg = FFmpeg 설치
not-now = 나중에
browse = 찾아보기...
diagnostics = 진단
run-this-before-reporting-an-export-problem-it-checks-f = 내보내기 문제를 제보하기 전에 실행하세요. FFmpeg, 출력 폴더, 인코더 및 게임 오디오를 확인합니다.
run-diagnostics = 진단 실행
copy-report = 보고서 복사
diagnostics-failed-unexpectedly = 진단 중 예기치 않은 오류가 발생했습니다.
orbitrender-is-not-ready-yet = OrbitRender가 아직 준비되지 않았습니다.
a-render-is-already-in-progress = 렌더가 이미 진행 중입니다.
open-a-custom-level-then-render = 커스텀 레벨을 연 후 렌더를 실행하세요.
open-a-custom-level-then-press-f6-to-render = 커스텀 레벨을 연 후 F6을 눌러 렌더를 실행하세요.
ffmpeg-installation-requires-your-confirmation-before-r = 렌더를 시작하려면 FFmpeg 설치를 먼저 확인해야 합니다.
preparing-render = {0}x{1} | 게임 {2} fps | 영상 {3} fps 준비 중 ({4} Mbps, {5})...
checking-value-encoder = {0} 인코더 확인 중...
ffmpeg-could-not-initialize-the-selected-encoder = FFmpeg가 선택한 인코더를 초기화하지 못했습니다.
hardware-encoder-failed-use-software-encoder-for-this-r = 하드웨어 인코더가 실패했습니다. 이번 렌더에 소프트웨어 인코더를 사용할까요?
encoder-preflight-failed-value = 인코더 사전 검사가 실패했습니다: {0}
checking-software-encoder-for-this-render = 이번 렌더에 사용할 소프트웨어 인코더를 확인 중...
render-cancelled-hardware-encoder-was-unavailable = 렌더를 취소했습니다. 하드웨어 인코더를 사용할 수 없습니다.
progress-percent = {0:F1}%
progress-frames = {0} / {1} 프레임   •   {2:F1} fps
progress-eta = 예상 시간 {0}   •   완료 예정 {1}
progress-speed = 실시간 대비 {0:F2}배   •   경과 {1}
progress-toast = 렌더링 중  {0:F1}%  |  {1} / {2} 프레임  |  {3:F1} fps  |  예상 {4}
render-cancelled = 렌더를 취소했습니다.
rendering-summary = {0}x{1} | 게임 {2} fps | 영상 {3} fps 렌더링 중
finalizing-container = {0} 마무리 중...
completed-frames = 완료: {0}프레임.
audio-mix-was-silent-check-game-sound-settings =  오디오 믹스가 무음입니다. 게임 사운드 설정을 확인하세요.
render-force-cancelled = 렌더를 강제로 취소했습니다.
render-failed-value = 렌더 실패: {0}
cleanup-failed-value = 정리 작업 실패: {0}
diagnostics-found-value-error-s-and-value-warning-s = 진단에서 오류 {0}개와 경고 {1}개를 발견했습니다.
diagnostics-passed-with-value-warning-s = 진단을 통과했지만 경고가 {0}개 있습니다.
all-diagnostics-passed = 모든 진단을 통과했습니다.
export-video = 영상 내보내기
export-video-selection = 선택 구간 영상 내보내기
select-at-least-two-tiles-to-export-a-selection = 먼저 Shift + 클릭으로 타일을 두 개 이상 선택하세요.
choose-the-settings-for-this-video-export = 영상 내보내기 설정을 선택하세요.
save-these-values-as-the-default-renderer-settings = 이 값을 렌더러 기본 설정으로 저장
cancel = 취소
ingame-fps-must-be-between-15-and-1024 = InGame FPS는 15~1024 사이여야 합니다.
video-fps-must-be-between-15-and-240 = Video FPS는 15~240 사이여야 합니다.
width-height-and-bitrate-must-be-valid-numbers = 너비, 높이 및 비트레이트는 유효한 숫자여야 합니다.
custom-values-are-outside-the-supported-ranges = 사용자 지정 값이 지원 범위를 벗어났습니다.
width-and-height-must-be-even-numbers = 너비와 높이는 짝수여야 합니다.
end-delay-must-be-between-0-and-30-seconds = 종료 지연은 0~30초 사이여야 합니다.
select-render-output-folder = 렌더 출력 폴더 선택
select-ffmpeg-executable = FFmpeg 실행 파일 선택
frames = 프레임
speed = 속도
complete = 완료
eta = 예상 시간
done = 완료
time-spent = 걸린 시간
copy-path = 경로 복사
the-render-window-will-update-when-the-next-stage-is-re = 다음 단계가 준비되면 렌더 상태가 업데이트됩니다.
hold-esc-for-1-second-to-cancel = 취소하려면 Esc를 1초간 누르세요
cancel-render = 렌더 취소
preparing = 준비 중
rendering = 렌더링 중
finalizing = 마무리 중
completed = 완료
cancelled = 취소됨
failed = 실패
status = 상태
preparing-your-export = 영상 내보내기 준비 중
rendering-video = 영상 렌더링 중
finishing-video = 영상 마무리 중
export-complete = 영상 내보내기 완료
render-cancelled-status = 렌더 취소됨
render-failed-status = 렌더 실패
render-status = 렌더 상태
output-file = 출력: {0}
duration-hours = {0}:{1:D2}:{2:D2}
duration-minutes = {0}:{1:D2}
encoder-confirmation = 인코더 확인
the-selected-hardware-encoder-could-not-be-initialized = 선택한 하드웨어 인코더를 초기화할 수 없습니다.
use-software-encoder-for-this-render-your-saved-encoder = 이번 렌더에 소프트웨어 인코더를 사용할까요? 저장된 인코더 설정은 변경되지 않습니다.
use-software-and-continue = 소프트웨어로 계속
ffmpeg-installation = FFMPEG 설치
installing-ffmpeg = FFMPEG 설치 중
orbitrender-needs-ffmpeg-to-export-videos-download-the = OrbitRender가 동영상을 내보내려면 FFmpeg가 필요합니다. 현재 플랫폼용 파일을 지금 다운로드할까요?
downloading-ffmpeg-for-this-platform-the-renderer-will = 현재 플랫폼용 FFmpeg를 다운로드하고 있습니다. 다운로드가 끝나면 렌더러를 사용할 수 있습니다.
the-download-comes-from-the-ffmpeg-build-provider-and-i = 다운로드는 FFmpeg 빌드 제공처에서 진행되며 모드 폴더에 저장됩니다. 인터넷 연결이 필요합니다.
custom = 사용자 지정
preview = 미리보기
encoding-speed = 인코딩 속도
maximum = 최대 속도
balanced = 균형
quality = 품질
video-encoder = 영상 인코더
auto = 자동
software = 소프트웨어
video-codec = 영상 코덱
video-bit-depth = 비트 깊이
ffmpeg-is-not-installed-waiting-for-your-confirmation-t = FFmpeg가 설치되지 않았습니다. 다운로드 확인을 기다리고 있습니다.
downloading-ffmpeg-for-this-platform = 현재 플랫폼용 FFmpeg를 다운로드하고 있습니다...
extracting-ffmpeg = FFmpeg 압축을 해제하고 있습니다...
installing-ffmpeg-binary = FFmpeg 실행 파일을 설치하고 있습니다...
ffmpeg-progress-percent = {0:F1}%
ffmpeg-progress-waiting-for-size = 다운로드 중...
ffmpeg-download-size = {0:F1} / {1:F1} MB
ffmpeg-download-size-unknown = 전체 다운로드 크기를 알 수 없음
ffmpeg-could-not-be-installed-automatically-value-check = FFmpeg를 자동으로 설치할 수 없습니다: {0}. 로그를 확인하거나 FFmpeg 실행 파일을 직접 지정하세요.
ffmpeg-installation-was-skipped-set-ffmpeg-executable-m = FFmpeg 설치를 건너뛰었습니다. 실행 파일을 직접 지정하거나 아래에서 설치하세요.
